{"uuid": "b377c8d2-04e8-4087-9a06-c037217776c5", "children": ["53f55e27-857e-4378-9f72-1c4f062456dc"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1707473811955, "stop": 1707473811955}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\pytest\\seleniumpytest\\env\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\pytest\\seleniumpytest\\env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 932, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\pytest\\seleniumpytest\\conftest.py\", line 32, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1707473812094, "stop": 1707473812105}], "start": 1707473811955, "stop": 1707473812106}